### ISSUE TITLE
Python port?

### ISSUE THREAD

**Issue by nickbien** [NElnour/capsule#1]
Thanks for your repo. I was wondering if you have or know, a package similar to yours, ported to python?

**Comment by NElnour** [comment]
> 

Not that I know of off the top of my head, but I dig around in HPA-related stuff and found this:[tsyu002/Human-Protein-Atlas-Image-Classifier]( https://github.com/tsyu002/Human-Protein-Atlas-Image-Classifier) referencing https://www.kaggle.com/competitions/human-protein-atlas-image-classification/overview/description. You might be able to find a similar package there
