### ISSUE TITLE
Error after running `whereIs`

### ISSUE THREAD

**Issue by nickbien** [NElnour/capsule#2]
Not sure what is happening but this error occurs only after the command.

```
   > whereIs("DVL2", enhanced)
    Error in if (grep(";", as.character(HPASet[hgnc_symbol, ]$Loci))) { : 
        argument is of length zero
```

**Comment by NElnour** [comment]
> Not sure what is happening but this error occurs only after the command.
> 
> ```
>    > whereIs("DVL2", enhanced)
>     Error in if (grep(";", as.character(HPASet[hgnc_symbol, ]$Loci))) { : 
>         argument is of length zero
> ```

let me look into it and get back to you

**Comment by NElnour** [comment]
@nickbien see merged changes for solution. Essentially, column labels from biomart changed, which is why whereIs couldn't find an entry for the gene even though it's there.
